services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      args:
        RAILS_ENV: development
        BUNDLE_DEPLOYMENT: 0
        BUNDLE_WITHOUT: "production"
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      HOME: /rails
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: password
    user: "${UID:-1000}:${GID:-1000}"

volumes:
  postgres_data: 